apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: deepface
  labels:
    language: python
spec:
  selector:
    matchLabels:
      app: deepface
  template:
    metadata:
      labels:
        app: deepface
    spec:
      serviceAccountName: deepface
      nodeSelector:
        role: production
        kind: gpu
        gpu: "true"
      containers:
        - name: deepface
          image: ${IMAGE_URL}:${IMAGE_TAG}
          resources:
            limits:
              nvidia.com/gpu: 1
          imagePullPolicy: Always
          command: ["gunicorn"]
          args:
            [
              "--workers=1",
              "--timeout=5400",
              "--bind=0.0.0.0:5000",
              "--access-logfile=-",
              "--error-logfile=-",
              "app:create_app()",
            ]
          ports:
            - name: http
              containerPort: ${PORT}
              protocol: TCP
