apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepface
  labels:
    language: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepface
  template:
    metadata:
      labels:
        app: deepface
    spec:
      serviceAccountName: deepface
      containers:
        - name: deepface
          image: ${IMAGE_URL}:${IMAGE_TAG}
          command: ["gunicorn"]
          args:
            [
              "--workers=1",
              "--timeout=5400",
              "--bind=0.0.0.0:5000",
              "--access-logfile=-",
              "--error-logfile=-",
              "app:create_app()",
            ]
          ports:
            - name: http
              containerPort: ${PORT}
              protocol: TCP
          resources:
            limits:
              memory: 4Gi
              cpu: 2000m
            requests:
              memory: 2Gi
              cpu: 1000m
