apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: deepface
  labels:
    app: deepface
    language: python
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deepface

  minReplicas: 1
  maxReplicas: 2

  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 100
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 100
