apiVersion: v1
kind: Service
metadata:
  name: deepface-gpu 
  labels:
    app: deepface-gpu
spec:
  type: ClusterIP
  ports:
    - port: ${PORT}
      targetPort: http
      protocol: TCP
      name: http